language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t liormb/docker-react -f Dockerfile.dev .

script:
  - docker run liormb/docker-react npm run test -- --coverage
